### PR TITLE
Added Resource Management Section

### PR DESCRIPTION
**Pull request by nickclark2016**
Link to the article added: https://medium.com/@pavlo.muratov/organizing-gpu-work-with-directed-acyclic-graphs-f3fd5f2c2af3

### CODE REVIEW

**Review by Pitj3 — APPROVED** [review]

**Comment by DethRaid** [comment]
I wouldn't put this resource in a "resource management" section. The section would be better named "render graph" imo, since the article is exactly about render graphs

**Comment by nickclark2016** [comment]
> I wouldn't put this resource in a "resource management" section. The section would be better named "render graph" imo, since the article is exactly about render graphs

I'd argue we try to keep it generic and go more specific as we get more resources/if needed.  Do you see us having lots of resources on render graphs?

**Comment by DethRaid** [comment]
Possibly? I can name three sources off the top of my head - TheMachinery blog, Granite engine blog, Frostbite GDC presentation - and it seems to come up reasonably often on the GP server

**Comment by nickclark2016** [comment]
> Possibly? I can name three sources off the top of my head - TheMachinery blog, Granite engine blog, Frostbite GDC presentation - and it seems to come up reasonably often on the GP server

Mind linking those here? I'll add them and then modify the section name.

**Comment by DethRaid** [comment]
[Our Machinery blog](https://ourmachinery.com/post/high-level-rendering-using-render-graphs/)
[Granite Engine Blog](https://themaister.net/blog/2017/08/15/render-graphs-and-vulkan-a-deep-dive/)
[Frostbite GDC presentation that started it all](https://www.slideshare.net/DICEStudio/framegraph-extensible-rendering-architecture-in-frostbite)

**Comment by DethRaid** [comment]
rip adding them and modifying the section name

**Comment by nickclark2016** [comment]
Oops. Got slammed and then forgot. I'll have them added in a bit

**Review by DethRaid — APPROVED** [review]

**Pull request merged**
